apiVersion: v1
kind: ConfigMap
metadata:
  name: my-html
  namespace: my-web-app
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>My Kubernetes App</title>
    </head>
    <body>
        <h1>Hello, Kubernetes!</h1>
        <p>This is a simple web server running in a Kubernetes cluster.</p>
    </body>
    </html>
