# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web
  namespace: my-web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-web
  template:
    metadata:
      labels:
        app: my-web
    spec:
      containers:
      - name: nginx
        image: nginx:stable-alpine
        ports:
        - containerPort: 80
        resources:
         # requests:
         #   memory: "64Mi"
         #   cpu: "100m"
         # limits:
         #   memory: "128Mi"
         #   cpu: "200m"
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-volume
        configMap:
          name: my-html
          items:
            - key: index.html
              path: index.html
