# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: my-web-service
  namespace: my-web-app
spec:
  selector:
    app: my-web
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30180
